---
abstract: 'API access to Billomat services'
author:
  - 'Aldo Calpini <dada@perl.it>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Billomat
provides:
  WWW::Billomat:
    file: lib/WWW/Billomat.pm
    version: 0.01
  WWW::Billomat::Client:
    file: lib/WWW/Billomat/Client.pm
    version: 0.01
  WWW::Billomat::Invoice:
    file: lib/WWW/Billomat/Invoice.pm
    version: 0.01
  WWW::Billomat::Invoice::Item:
    file: lib/WWW/Billomat/Invoice/Item.pm
    version: 0.01
requires:
  JSON: 0
  Moose: 0
  MooseX::ClassAttribute: 0
  REST::Client: 0
  perl: 5.01
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dada/WWW-Billomat
version: 0.01
